In [194]:
import pprint
import pandas as pd
import numpy as np
import re
import time
import datetime

import math
import cmath
from collections import Counter

In [195]:
# Read the txt file

file_path = 'resources/day11_input_test.txt'

# Open the file and read its contents using readlines()
with open(file_path, 'r') as file:
    text = file.read()
print(text)

...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....


In [385]:
# Read the txt file

file_path = 'resources/day11_input.txt'

# Read the input file and store grids as list of lists
grids = []
current_grid = []

with open(file_path, 'r') as file:
    for line in file:
        line = line.strip()
        if line:  # Check if the line is not empty
            current_grid.append(list(line))  # Append each line as a list of characters
        else:  # Empty line indicates the end of the current grid
            if current_grid:
                grids.append(current_grid)  # Add the completed grid to the list
                current_grid = []  # Reset for the next grid (if any)

# If there's any remaining grid at the end of the file, add it
if current_grid:
    grids.append(current_grid)

# Display each grid separately (as list of lists)
for idx, grid in enumerate(grids, start=1):
    print(f"Grid {idx}:")
    for row in grid:
        print(''.join(row))
    print()

print(grids)

Grid 1:
...........................#.............#..........#.........#..................#.......#.............................................#....
..............#...........................................................................................#...............#.................
.....................#......................................................................................................................
...................................#................................#................................................#....................#.
.................#.......................................................#..........#..................#.............................#......
...............................................................................................#.................#..........................
......................................................#........................#........................................#...................
.....

## PART 1

In [386]:
# Convert characters to integers: '.' to 0 and '#' to 1
for grid in grids:
    converted_list = [[0 if char == '.' else 1 for char in row] for row in grid]
    print(converted_list)

    # Convert the list of lists to a NumPy array
    arr = np.array(converted_list)
    print("2D NumPy array:")
    print(arr)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [387]:
#The script first identifies the indices of rows with only zeros, then inserts the same row below each identified row. 

rows_to_insert = []

for i, row in enumerate(arr):
    if np.array_equal(row, np.zeros_like(row)):
        rows_to_insert.append(i)

for index in sorted(rows_to_insert, reverse=True):
    arr = np.insert(arr, index+1, arr[index], axis=0)

print(arr)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [388]:
#Transpose the array above and do the same for the columns

#The script first identifies the indices of columns with only zeros, then inserts the same columns below each identified column. 

transposed_arr = arr.T

rows_to_insert = []

for i, row in enumerate(transposed_arr):
    if np.array_equal(row, np.zeros_like(row)):
        rows_to_insert.append(i)

for index in sorted(rows_to_insert, reverse=True):
    transposed_arr = np.insert(transposed_arr, index+1, transposed_arr[index], axis=0)

arr = transposed_arr.T
print(arr)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [389]:
# Convert 0 to '.' and 1 to '#' within the array
converted_arr = np.where(arr == 0, '.', '#')

# Convert the NumPy array to a list of lists
galaxy_list = converted_arr.tolist()
print(galaxy_list)
print()
# Print the resulting list of lists
for galaxy in galaxy_list:
    print(' '.join(galaxy))

[['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '#', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '#', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '#', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '#', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '#', '.', '.', '.', '.', '.', '.', '.', '#', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '#', '.', '.', '.', '.'], ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '#', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '

In [390]:
# Initialize a counter for unique numbering
counter = 1

# Iterate through the array and replace each 1 with a unique number
for i in range(arr.shape[0]): #row 
    for j in range(arr.shape[1]): #column
        if arr[i, j] == 1:
            arr[i, j] = counter
            counter += 1
print(arr)

# Find the maximum value in the array
largest_galaxy = np.max(arr)
print("Largest integer:", largest_galaxy)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Largest integer: 438


In [391]:
galaxies_index = []
for galaxy in range(1,largest_galaxy+1,1):
    gal_index = np.where(arr == galaxy)
    gal_index = [[i, j] for i, j in zip(gal_index[0], gal_index[1])] # keep as list in a list instead of array
    galaxies_index.append(gal_index)

short_path_arr = np.zeros((largest_galaxy,largest_galaxy), dtype=int)

for i, value in enumerate(galaxies_index):
    print(value[0])
    for j in range(0,len(galaxies_index),1):
        if short_path_arr[i][j]== 0:
            # print(value[0])
            # print(value[0][0])
            # print(value[0][1])
           # print(galaxies_index[j][0][0])
            path = abs(galaxies_index[i][0][0] - galaxies_index[j][0][0]) + abs(galaxies_index[i][0][1] - galaxies_index[j][0][1])
            short_path_arr[i][j] = path
            
    
    
print(galaxies_index)
print(short_path_arr)

# print(galaxies_index[0])
# print(galaxies_index[0][0])
# print(galaxies_index[0][0][0])
# print(galaxies_index[0][0][1])
# print(galaxies_index[1][0])
# print(galaxies_index[1][0][0])
# print(galaxies_index[1][0][1])

# print(short_path_arr)
# print(short_path_arr[0][1])
# # print(short_path_arr[0][1])

[0, 28]
[0, 42]
[0, 54]
[0, 65]
[0, 85]
[0, 93]
[0, 140]
[1, 15]
[1, 110]
[1, 127]
[2, 22]
[3, 36]
[3, 72]
[3, 121]
[3, 143]
[4, 18]
[4, 77]
[4, 88]
[4, 107]
[4, 138]
[5, 99]
[5, 117]
[6, 56]
[6, 83]
[6, 125]
[7, 9]
[7, 65]
[7, 94]
[7, 112]
[8, 42]
[8, 48]
[8, 132]
[9, 28]
[9, 89]
[9, 142]
[10, 5]
[10, 74]
[10, 136]
[11, 14]
[11, 58]
[11, 100]
[11, 118]
[11, 129]
[12, 45]
[13, 1]
[13, 18]
[13, 40]
[13, 80]
[13, 110]
[13, 144]
[14, 29]
[14, 50]
[15, 103]
[15, 114]
[16, 8]
[16, 21]
[16, 65]
[16, 75]
[16, 134]
[17, 15]
[17, 84]
[17, 95]
[17, 125]
[18, 33]
[18, 142]
[19, 48]
[19, 105]
[19, 117]
[20, 0]
[20, 67]
[21, 13]
[21, 20]
[21, 57]
[21, 112]
[21, 127]
[21, 137]
[22, 91]
[23, 37]
[23, 64]
[23, 72]
[23, 100]
[24, 10]
[24, 16]
[24, 30]
[24, 43]
[24, 84]
[24, 122]
[25, 110]
[25, 116]
[25, 133]
[25, 144]
[26, 58]
[27, 27]
[28, 4]
[28, 75]
[28, 127]
[29, 22]
[29, 67]
[29, 96]
[29, 106]
[30, 12]
[30, 38]
[30, 81]
[30, 88]
[30, 139]
[31, 0]
[31, 100]
[31, 119]
[31, 133]
[32, 29]
[32, 43]
[32

In [392]:
len(short_path_arr)

438

In [393]:
total_sum = 0
for i in range(0,len(galaxies_index),1):
    sum_diag = np.diagonal(short_path_arr, offset=i)
    print(sum_diag)
    total_sum += np.diagonal(short_path_arr, offset=i).sum()
    
print("Total sums of upper diagonal:", total_sum)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[ 14  12  11  20   8  47 126  95  17 106  15  36  49  22 126  59  11  19
  31  40  18  62  27  42 117  56  29  

In [205]:
# # Extract the elements of the first upper diagonal (offset = 1)
# upper_diagonal = np.diagonal(short_path_arr, offset=2)

# # # Calculate the sum of diagonal elements
# # diagonal_sum = np.diagonal(arr).sum()

# print("Elements of the first upper diagonal:", upper_diagonal)

## PART 2 - ARRAY

In [210]:
# Convert characters to integers: '.' to 0 and '#' to 1
for grid in grids:
    converted_list = [[0 if char == '.' else 1 for char in row] for row in grid]
    print(converted_list)

    # Convert the list of lists to a NumPy array
    arr = np.array(converted_list)
    print("2D NumPy array:")
    print(arr)


#expand rows
rows_to_insert = []
count = 0

for i, row in enumerate(arr):
    if np.array_equal(row, np.zeros_like(row)):
        print(i)
        rows_to_insert.extend([i] * (10-1))  # Append the index 1000000 times

print(rows_to_insert)
for index in sorted(rows_to_insert, reverse=True):
    arr = np.insert(arr, index+1, arr[index], axis=0)

print(arr)

#expand columns

#Transpose the array above and do the same for the columns

#The script first identifies the indices of columns with only zeros, then inserts the same columns below each identified column. 

transposed_arr = arr.T

cols_to_insert = []
count = 0

for i, col in enumerate(transposed_arr):
    if np.array_equal(col, np.zeros_like(col)):
        print(i)
        cols_to_insert.extend([i] * (10-1))  # Append the index 1000000 times

print(cols_to_insert)
for index in sorted(cols_to_insert, reverse=True):
    transposed_arr = np.insert(transposed_arr, index+1, transposed_arr[index], axis=0)

arr = transposed_arr.T
print(arr)


[[0, 0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [1, 0, 0, 0, 1, 0, 0, 0, 0, 0]]
2D NumPy array:
[[0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 1 0 0 0 0 0]]
3
7
[3, 3, 3, 3, 3, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7]
[[0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0

In [211]:
# Initialize a counter for unique numbering
counter = 1

# Iterate through the array and replace each 1 with a unique number
for i in range(arr.shape[0]): #row 
    for j in range(arr.shape[1]): #column
        if arr[i, j] == 1:
            arr[i, j] = counter
            counter += 1
print(arr)

# Find the maximum value in the array
largest_galaxy = np.max(arr)
print("Largest integer:", largest_galaxy)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [3 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [8 0 0 ... 0 0 0]]
Largest integer: 9


In [212]:
galaxies_index = []
for galaxy in range(1,largest_galaxy+1,1):
    gal_index = np.where(arr == galaxy)
    gal_index = [[i, j] for i, j in zip(gal_index[0], gal_index[1])] # keep as list in a list instead of array
    galaxies_index.append(gal_index)

short_path_arr = np.zeros((largest_galaxy,largest_galaxy), dtype=int)

for i, value in enumerate(galaxies_index):
    print(value[0])
    for j in range(0,len(galaxies_index),1):
        if short_path_arr[i][j]== 0:
            # print(value[0])
            # print(value[0][0])
            # print(value[0][1])
           # print(galaxies_index[j][0][0])
            path = abs(galaxies_index[i][0][0] - galaxies_index[j][0][0]) + abs(galaxies_index[i][0][1] - galaxies_index[j][0][1])
            short_path_arr[i][j] = path
            
    
    
print(galaxies_index)
print(short_path_arr)

[0, 12]
[1, 25]
[2, 0]
[13, 24]
[14, 1]
[15, 36]
[26, 25]
[27, 0]
[27, 13]
[[[0, 12]], [[1, 25]], [[2, 0]], [[13, 24]], [[14, 1]], [[15, 36]], [[26, 25]], [[27, 0]], [[27, 13]]]
[[ 0 14 14 25 25 39 39 39 28]
 [14  0 26 13 37 25 25 51 38]
 [14 26  0 35 13 49 49 25 38]
 [25 13 35  0 24 14 14 38 25]
 [25 37 13 24  0 36 36 14 25]
 [39 25 49 14 36  0 22 48 35]
 [39 25 49 14 36 22  0 26 13]
 [39 51 25 38 14 48 26  0 13]
 [28 38 38 25 25 35 13 13  0]]


In [213]:
total_sum = 0
for i in range(0,len(galaxies_index),1):
    sum_diag = np.diagonal(short_path_arr, offset=i)
    print(sum_diag)
    total_sum += np.diagonal(short_path_arr, offset=i).sum()
    
print("Total sums of upper diagonal:", total_sum)

[0 0 0 0 0 0 0 0 0]
[14 26 35 24 36 22 26 13]
[14 13 13 14 36 48 13]
[25 37 49 14 14 35]
[25 25 49 38 25]
[39 25 25 25]
[39 51 38]
[39 38]
[28]
Total sums of upper diagonal: 1030


The above expansion code does not work for sparse matrix with 1 million expansion

## PART 2 - MODIFY FOR MILLIONS EXPANSION
Since we cannot expand the sparse array by the millions, let's work with only the index numbering expand and therefore no need to store the matrix but only keep the indexes and manipulate indexes arithmetric

In [394]:
# Read the txt file

file_path = 'resources/day11_input.txt'

# Read the input file and store grids as list of lists
grids = []
current_grid = []

with open(file_path, 'r') as file:
    for line in file:
        line = line.strip()
        if line:  # Check if the line is not empty
            current_grid.append(list(line))  # Append each line as a list of characters
        else:  # Empty line indicates the end of the current grid
            if current_grid:
                grids.append(current_grid)  # Add the completed grid to the list
                current_grid = []  # Reset for the next grid (if any)

# If there's any remaining grid at the end of the file, add it
if current_grid:
    grids.append(current_grid)

# Display each grid separately (as list of lists)
for idx, grid in enumerate(grids, start=1):
    print(f"Grid {idx}:")
    for row in grid:
        print(''.join(row))
    print()

print(grids)

Grid 1:
...........................#.............#..........#.........#..................#.......#.............................................#....
..............#...........................................................................................#...............#.................
.....................#......................................................................................................................
...................................#................................#................................................#....................#.
.................#.......................................................#..........#..................#.............................#......
...............................................................................................#.................#..........................
......................................................#........................#........................................#...................
.....

In [395]:
# Convert characters to integers: '.' to 0 and '#' to 1
for grid in grids:
    converted_list = [[0 if char == '.' else 1 for char in row] for row in grid]
    print(converted_list)

    # Convert the list of lists to a NumPy array
    arr = np.array(converted_list)
    print("2D NumPy array:")
    print(arr)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [396]:
#The script first identifies the indices of rows with only zeros, then inserts the same row below each identified row. 

rows_to_insert = []
count = 0

for i, row in enumerate(arr):
    if np.array_equal(row, np.zeros_like(row)):
        print(i)
        count +=1
        #rows_add = count*9
        rows_add = 1000000 - 1
        rows_to_insert.append([i,rows_add])
        #rows_to_insert.extend([i] * (1000000-1))  # Append the index 1000000 times

print(rows_to_insert)
# for index in sorted(rows_to_insert, reverse=True):
#     arr = np.insert(arr, index+1, arr[index], axis=0)

print(arr)

57
69
76
93
96
109
118
[[57, 999999], [69, 999999], [76, 999999], [93, 999999], [96, 999999], [109, 999999], [118, 999999]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [397]:
#Transpose the array above and do the same for the columns

#The script first identifies the indices of columns with only zeros, then inserts the same columns below each identified column. 

transposed_arr = arr.T

cols_to_insert = []
count = 0

for i, col in enumerate(transposed_arr):
    if np.array_equal(col, np.zeros_like(col)):
        print(i)
        count +=1
        # cols_add = count*9
        cols_add = 1000000 - 1
        cols_to_insert.append([i,cols_add])
        # rows_to_insert.extend([i] * (1000000-1))  # Append the index 1000000 times

print(cols_to_insert)
# for index in sorted(rows_to_insert, reverse=True):
#     transposed_arr = np.insert(transposed_arr, index+1, transposed_arr[index], axis=0)

arr = transposed_arr.T
print(arr)

6
50
59
67
119
[[6, 999999], [50, 999999], [59, 999999], [67, 999999], [119, 999999]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [398]:
# Initialize a counter for unique numbering
counter = 1

# Iterate through the array and replace each 1 with a unique number
for i in range(arr.shape[0]): #row 
    for j in range(arr.shape[1]): #column
        if arr[i, j] == 1:
            arr[i, j] = counter
            counter += 1
print(arr)

# Find the maximum value in the array
largest_galaxy = np.max(arr)
print("Largest integer:", largest_galaxy)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Largest integer: 438


In [399]:
galaxies_index = []
for galaxy in range(1,largest_galaxy+1,1):
    gal_index = np.where(arr == galaxy)
    gal_index = [[i, j] for i, j in zip(gal_index[0], gal_index[1])] # keep as list in a list instead of array
    galaxies_index.append(gal_index)


print(galaxies_index)

# Create a reversed version of rows_to_insert using slicing
rows_to_insert = rows_to_insert[::-1]

# Create a reversed version of cols_to_insert using slicing
cols_to_insert = cols_to_insert[::-1]

print(f'Rows that are affected: {rows_to_insert}')
print(f'Cols that are affected: {cols_to_insert}')

# Find elements in the first list meeting the conditions and modify them

print(f'Start Row Mod')
print()
for row in rows_to_insert:
    for galaxy in galaxies_index:
        print(galaxy)
        print(galaxy[0][0])
        if galaxy[0][0] == row[0] or galaxy[0][0] > row[0]:
            galaxy[0][0] += row[1]
            print(f'Changed: {galaxy[0][0]}')

print()
print(f'Start Col Mod')
print()
for col in cols_to_insert:
    for galaxy in galaxies_index:
        print(galaxy)
        print(galaxy[0][1])
        if galaxy[0][1] == col[0] or galaxy[0][1] > col[0]:
             galaxy[0][1] += col[1]
             print(f'Changed: {galaxy[0][1]}')

# for galaxy in galaxies_index:
#     print(galaxy[0][0])
#     for row in rows_to_insert: 
#         #print(row)
#         #print(row[0])
#         if galaxy[0][0] == row[0] or galaxy[0][0] > row[0]:
#             galaxy[0][0] += row[1]
#             print(f'Changed: {galaxy[0][0]}')

print("Modified galaxies:", galaxies_index)

[[[0, 27]], [[0, 41]], [[0, 52]], [[0, 62]], [[0, 81]], [[0, 89]], [[0, 135]], [[1, 14]], [[1, 106]], [[1, 122]], [[2, 21]], [[3, 35]], [[3, 68]], [[3, 117]], [[3, 138]], [[4, 17]], [[4, 73]], [[4, 84]], [[4, 103]], [[4, 133]], [[5, 95]], [[5, 113]], [[6, 54]], [[6, 79]], [[6, 120]], [[7, 8]], [[7, 62]], [[7, 90]], [[7, 108]], [[8, 41]], [[8, 47]], [[8, 127]], [[9, 27]], [[9, 85]], [[9, 137]], [[10, 5]], [[10, 70]], [[10, 131]], [[11, 13]], [[11, 56]], [[11, 96]], [[11, 114]], [[11, 124]], [[12, 44]], [[13, 1]], [[13, 17]], [[13, 39]], [[13, 76]], [[13, 106]], [[13, 139]], [[14, 28]], [[14, 49]], [[15, 99]], [[15, 110]], [[16, 7]], [[16, 20]], [[16, 62]], [[16, 71]], [[16, 129]], [[17, 14]], [[17, 80]], [[17, 91]], [[17, 120]], [[18, 32]], [[18, 137]], [[19, 47]], [[19, 101]], [[19, 113]], [[20, 0]], [[20, 64]], [[21, 12]], [[21, 19]], [[21, 55]], [[21, 108]], [[21, 122]], [[21, 132]], [[22, 87]], [[23, 36]], [[23, 61]], [[23, 68]], [[23, 96]], [[24, 9]], [[24, 15]], [[24, 29]], [[24, 

In [400]:
galaxies_index

[[[0, 1000026]],
 [[0, 1000040]],
 [[0, 2000050]],
 [[0, 3000059]],
 [[0, 4000077]],
 [[0, 4000085]],
 [[0, 5000130]],
 [[1, 1000013]],
 [[1, 4000102]],
 [[1, 5000117]],
 [[2, 1000020]],
 [[3, 1000034]],
 [[3, 4000064]],
 [[3, 4000113]],
 [[3, 5000133]],
 [[4, 1000016]],
 [[4, 4000069]],
 [[4, 4000080]],
 [[4, 4000099]],
 [[4, 5000128]],
 [[5, 4000091]],
 [[5, 4000109]],
 [[6, 2000052]],
 [[6, 4000075]],
 [[6, 5000115]],
 [[7, 1000007]],
 [[7, 3000059]],
 [[7, 4000086]],
 [[7, 4000104]],
 [[8, 1000040]],
 [[8, 1000046]],
 [[8, 5000122]],
 [[9, 1000026]],
 [[9, 4000081]],
 [[9, 5000132]],
 [[10, 5]],
 [[10, 4000066]],
 [[10, 5000126]],
 [[11, 1000012]],
 [[11, 2000054]],
 [[11, 4000092]],
 [[11, 4000110]],
 [[11, 5000119]],
 [[12, 1000043]],
 [[13, 1]],
 [[13, 1000016]],
 [[13, 1000038]],
 [[13, 4000072]],
 [[13, 4000102]],
 [[13, 5000134]],
 [[14, 1000027]],
 [[14, 1000048]],
 [[15, 4000095]],
 [[15, 4000106]],
 [[16, 1000006]],
 [[16, 1000019]],
 [[16, 3000059]],
 [[16, 4000067]],
 [[

In [401]:
# path = 0
# count = 0 
# for i,gal_idx in enumerate(galaxies_index):
#     print(galaxies_index[i][0])
#     # print(galaxies_index[i][0][0])
#     # print(galaxies_index[i][0][1])
#     for j in range(1,k,1):
#         path_list = []
#         # print('Printing j')
#         print(galaxies_index[j][0])
#         # print(galaxies_index[j][0][0])
#         # print(galaxies_index[j][0][1])
#         row_path = abs(galaxies_index[i][0][0] - galaxies_index[j][0][0])
#         col_path = abs(galaxies_index[i][0][1] - galaxies_index[j][0][1])
#         path_add = row_path + col_path
#         print(f'{row_path} and {col_path}')
#         print(f'New value to add: {path_add}')
#         path += path_add
#         print(path)
#         count +=1
        
# print(f'Total Sum After Expansion: {path}')

In [402]:
 all_path = []

for i,gal_idx in enumerate(galaxies_index):
    path_list = []
    print(galaxies_index[i][0])
    print(i)
    # print(galaxies_index[i][0][0])
    # print(galaxies_index[i][0][1])
    for j in range(1,k,1):
        # print('Printing j')
        print(galaxies_index[j][0])
        # print(galaxies_index[j][0][0])
        # print(galaxies_index[j][0][1])
        row_path = abs(galaxies_index[i][0][0] - galaxies_index[j][0][0])
        col_path = abs(galaxies_index[i][0][1] - galaxies_index[j][0][1])
        path_add = row_path + col_path
        print(f'{row_path} and {col_path}')
        print(f'New value to add: {path_add}')
        path_list.append(path_add)
    if all_path:
        print(i)
        print("List without the first i element:", path_list[i:])
        # print("Next list:", path_list)
        all_path.extend(path_list[i:])
        # all_path = all_path + path_list[i:]
        print(f'After ADDING: {all_path}')
        
    else: 
        print("First list:", path_list)
        all_path.extend(path_list)
        
print(f'After Expansion: {all_path}')
print(f'Total Sum After Expansion: {sum(all_path)}')

[0, 1000026]
0
[0, 1000040]
0 and 14
New value to add: 14
[0, 2000050]
0 and 1000024
New value to add: 1000024
[0, 3000059]
0 and 2000033
New value to add: 2000033
[0, 4000077]
0 and 3000051
New value to add: 3000051
[0, 4000085]
0 and 3000059
New value to add: 3000059
[0, 5000130]
0 and 4000104
New value to add: 4000104
[1, 1000013]
1 and 13
New value to add: 14
[1, 4000102]
1 and 3000076
New value to add: 3000077
First list: [14, 1000024, 2000033, 3000051, 3000059, 4000104, 14, 3000077]
[0, 1000040]
1
[0, 1000040]
0 and 0
New value to add: 0
[0, 2000050]
0 and 1000010
New value to add: 1000010
[0, 3000059]
0 and 2000019
New value to add: 2000019
[0, 4000077]
0 and 3000037
New value to add: 3000037
[0, 4000085]
0 and 3000045
New value to add: 3000045
[0, 5000130]
0 and 4000090
New value to add: 4000090
[1, 1000013]
1 and 27
New value to add: 28
[1, 4000102]
1 and 3000062
New value to add: 3000063
1
List without the first i element: [1000010, 2000019, 3000037, 3000045, 4000090, 28, 300

In [403]:
print(f'Total Sum After Expansion: {sum(all_path)}')

Total Sum After Expansion: 66001640
